In [1]:
import numpy as np


def softmax_func(normalized):
    raised = np.exp(normalized)
    # print(raised)
    # print(np.sum(raised, axis=1).reshape(-1, 1))
    output = raised / np.sum(raised, axis=1).reshape(-1, 1)
    return output

In [2]:
x = np.random.rand(5, 3)
x

array([[0.47187077, 0.76302755, 0.56155227],
       [0.40918266, 0.78664404, 0.44165394],
       [0.43293021, 0.58393805, 0.63391431],
       [0.38575621, 0.14596001, 0.65056805],
       [0.54297384, 0.33804416, 0.76072034]])

In [3]:
y = np.zeros_like(x)
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
inds = (np.arange(0,y.shape[0]), np.random.randint(0, 3, size=y.shape[0]))
inds

(array([0, 1, 2, 3, 4]), array([2, 1, 2, 1, 0], dtype=int32))

In [5]:
y[inds] = 1
y

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [6]:
softmax_func(x)

array([[0.29139226, 0.38987536, 0.31873238],
       [0.28640318, 0.41774112, 0.2958557 ],
       [0.29536765, 0.34351428, 0.36111807],
       [0.32362733, 0.25462616, 0.42174652],
       [0.32701364, 0.26641952, 0.40656685]])

In [7]:
normalized = x - np.max(x, axis=-1).reshape(-1,1)
normalized

array([[-0.29115678,  0.        , -0.20147528],
       [-0.37746138,  0.        , -0.3449901 ],
       [-0.2009841 , -0.04997627,  0.        ],
       [-0.26481184, -0.50460805,  0.        ],
       [-0.2177465 , -0.42267617,  0.        ]])

In [8]:
softmax_func(normalized)

array([[0.29139226, 0.38987536, 0.31873238],
       [0.28640318, 0.41774112, 0.2958557 ],
       [0.29536765, 0.34351428, 0.36111807],
       [0.32362733, 0.25462616, 0.42174652],
       [0.32701364, 0.26641952, 0.40656685]])

In [9]:
raised = np.exp(x) # step 1
summed = np.sum(raised, axis=-1).reshape(-1,1) # step 2.  reshape so each row has 1 column.
pow = summed ** -1 # step 3
staged_softmax = raised * pow # step 4

In [10]:
staged_softmax

array([[0.29139226, 0.38987536, 0.31873238],
       [0.28640318, 0.41774112, 0.2958557 ],
       [0.29536765, 0.34351428, 0.36111807],
       [0.32362733, 0.25462616, 0.42174652],
       [0.32701364, 0.26641952, 0.40656685]])

In [11]:
def nll_grad(y, pred):
    return -1 * y / pred

loss_grad = nll_grad(y, staged_softmax)

In [12]:
loss_grad

array([[-0.        , -0.        , -3.13742832],
       [-0.        , -2.39382705, -0.        ],
       [-0.        , -0.        , -2.76917744],
       [-0.        , -3.92732628, -0.        ],
       [-3.05797646, -0.        , -0.        ]])

In [ ]:
raised = np.exp(x) # step 1
summed = np.sum(raised, axis=-1).reshape(-1,1) # step 2.  reshape so each row has 1 column.
pow = summed ** -1 # step 3
staged_softmax = raised * pow # step 4

### Derivative of raised, we should pay attention to the sizes of matrixes

In [16]:
raised

array([[1.60299021, 2.14475976, 1.75339212],
       [1.50558671, 2.19601431, 1.55527743],
       [1.54176862, 1.7930858 , 1.88497453],
       [1.47072608, 1.15714991, 1.91662926],
       [1.72111759, 1.40220243, 2.13981706]])

In [14]:
raised_grad = loss_grad * pow
raised_grad

array([[-0.        , -0.        , -0.57032308],
       [-0.        , -0.45537044, -0.        ],
       [-0.        , -0.        , -0.53051115],
       [-0.        , -0.86419227, -0.        ],
       [-0.58101783, -0.        , -0.        ]])

In [17]:
pow

array([[0.18178043],
       [0.19022696],
       [0.19157716],
       [0.22004596],
       [0.19000075]])

In [18]:
pow_grad = loss_grad * raised
pow_grad

array([[-0.        , -0.        , -5.50114209],
       [-0.        , -5.25687845, -0.        ],
       [-0.        , -0.        , -5.21982895],
       [-0.        , -4.54450525, -0.        ],
       [-5.26313708, -0.        , -0.        ]])

#### shape of pow_grad must be same as pow_grad

In [19]:
pow_grad = np.sum(pow_grad, axis=-1).reshape(-1, 1)
pow_grad

array([[-5.50114209],
       [-5.25687845],
       [-5.21982895],
       [-4.54450525],
       [-5.26313708]])

In [20]:
summed

array([[5.50114209],
       [5.25687845],
       [5.21982895],
       [4.54450525],
       [5.26313708]])

In [21]:
summed_grad = (-1 * summed ** -2) * pow_grad
summed_grad

array([[0.18178043],
       [0.19022696],
       [0.19157716],
       [0.22004596],
       [0.19000075]])

### we have 2 path for the raised grad

In [22]:
raised_grad_2 = np.ones_like(raised) * summed_grad
raised_grad_2

array([[0.18178043, 0.18178043, 0.18178043],
       [0.19022696, 0.19022696, 0.19022696],
       [0.19157716, 0.19157716, 0.19157716],
       [0.22004596, 0.22004596, 0.22004596],
       [0.19000075, 0.19000075, 0.19000075]])

#### Combine 2 raised path

In [26]:
raised_grad += raised_grad_2

In [27]:
staged_softmax

array([[0.29139226, 0.38987536, 0.31873238],
       [0.28640318, 0.41774112, 0.2958557 ],
       [0.29536765, 0.34351428, 0.36111807],
       [0.32362733, 0.25462616, 0.42174652],
       [0.32701364, 0.26641952, 0.40656685]])

In [28]:
staged_softmax_grad = raised_grad * np.exp(x)
staged_softmax_grad

array([[ 0.29139226,  0.38987536, -0.68126762],
       [ 0.28640318, -0.58225888,  0.2958557 ],
       [ 0.29536765,  0.34351428, -0.63888193],
       [ 0.32362733, -0.74537384,  0.42174652],
       [-0.67298636,  0.26641952,  0.40656685]])

In [30]:
y.shape, staged_softmax.shape

((5, 3), (5, 3))

In [32]:
staged_softmax - y

array([[ 0.29139226,  0.38987536, -0.68126762],
       [ 0.28640318, -0.58225888,  0.2958557 ],
       [ 0.29536765,  0.34351428, -0.63888193],
       [ 0.32362733, -0.74537384,  0.42174652],
       [-0.67298636,  0.26641952,  0.40656685]])

### check J * loss in a function

In [33]:
def softmax_grad_func(softmax, loss_grad):
    output = np.zeros_like(softmax)
    for i in range(softmax.shape[0]):
        sm_row = softmax[i,:]
        sm_grad = (-np.outer(sm_row, sm_row) + np.diag(sm_row.flatten()))
        row_grad = sm_grad * loss_grad[i,:].reshape(1,-1)
        output[i,:] = np.sum(row_grad, -1)
    return output

In [34]:
derived_softmax_grad = softmax_grad_func(staged_softmax, loss_grad)
derived_softmax_grad

array([[ 0.29139226,  0.38987536, -0.68126762],
       [ 0.28640318, -0.58225888,  0.2958557 ],
       [ 0.29536765,  0.34351428, -0.63888193],
       [ 0.32362733, -0.74537384,  0.42174652],
       [-0.67298636,  0.26641952,  0.40656685]])

In [35]:
np.allclose(derived_softmax_grad, staged_softmax_grad)

True